# CHEDDAR parameter files used as fixtures by the tests of the parameter-file
# import. bootparam_35.json is parameters/bootparam_35.json from
# scale-snu/cheddar-fhe at 307b49cbe03e7f8f14bf31485f716c1090c9ec9d, reformatted
# by the repository's hooks (MIT License, Copyright 2026 Scalable Computer
# Architecture Laboratory, Seoul National University).

package(
    default_applicable_licenses = ["@heir//:license"],
    default_visibility = ["//visibility:public"],
)

filegroup(
    name = "parameter_files",
    srcs = ["bootparam_35.json"],
)
