#include "lib/Dialect/Cheddar/Transforms/PrepareLinearTransforms.h"

#include <string>

#include "lib/Dialect/Cheddar/IR/CheddarOps.h"
#include "lib/Dialect/Cheddar/IR/CheddarTypes.h"
#include "llvm/include/llvm/ADT/SetVector.h"             // from @llvm-project
#include "llvm/include/llvm/ADT/SmallVector.h"           // from @llvm-project
#include "mlir/include/mlir/Analysis/SliceAnalysis.h"    // from @llvm-project
#include "mlir/include/mlir/Dialect/Func/IR/FuncOps.h"   // from @llvm-project
#include "mlir/include/mlir/Dialect/Tensor/IR/Tensor.h"  // from @llvm-project
#include "mlir/include/mlir/IR/BuiltinAttributes.h"      // from @llvm-project
#include "mlir/include/mlir/IR/BuiltinOps.h"             // from @llvm-project
#include "mlir/include/mlir/IR/BuiltinTypes.h"           // from @llvm-project
#include "mlir/include/mlir/IR/IRMapping.h"              // from @llvm-project
#include "mlir/include/mlir/IR/Operation.h"              // from @llvm-project
#include "mlir/include/mlir/IR/SymbolTable.h"            // from @llvm-project
#include "mlir/include/mlir/Support/LLVM.h"              // from @llvm-project
#include "mlir/include/mlir/Support/LogicalResult.h"     // from @llvm-project

namespace mlir::heir::cheddar {

#define GEN_PASS_DEF_CHEDDARPREPARELINEARTRANSFORMS
#include "lib/Dialect/Cheddar/Transforms/PrepareLinearTransforms.h.inc"

namespace {

// Find the wrapper calls generated by split-preprocessing. The preprocessing
// result is passed directly to the paired preprocessed call, which makes the
// pair unambiguous even when a module contains multiple entry functions.
static FailureOr<std::pair<func::CallOp, func::CallOp>> findCallPair(
    ModuleOp module, func::FuncOp preprocessing, func::FuncOp preprocessed) {
  func::CallOp foundPack;
  func::CallOp foundEval;
  module.walk([&](func::CallOp call) {
    if (foundEval || call.getCallee() != preprocessed.getName()) return;
    for (Value operand : call.getOperands()) {
      auto pack = operand.getDefiningOp<func::CallOp>();
      if (pack && pack.getCallee() == preprocessing.getName()) {
        foundPack = pack;
        foundEval = call;
        return;
      }
    }
  });
  if (!foundPack || !foundEval) return failure();
  return std::make_pair(foundPack, foundEval);
}

static void appendFunctionResult(func::FuncOp func, Type type, Value value) {
  SmallVector<Type> results(func.getResultTypes());
  results.push_back(type);
  func.setFunctionType(
      FunctionType::get(func.getContext(), func.getArgumentTypes(), results));
  auto ret = cast<func::ReturnOp>(func.getBody().front().getTerminator());
  ret.getOperandsMutable().append(value);
}

static Operation* createPrepareOp(OpBuilder& builder, Location loc,
                                  LinearTransformOp raw, Value ctx,
                                  Value diagonals, Value output,
                                  Type resultType) {
  OperationState state(loc, PrepareLinearTransformOp::getOperationName());
  state.addOperands({ctx, diagonals, output});
  state.addTypes(resultType);
  state.addAttributes(raw->getAttrs());
  return builder.create(state);
}

static Operation* createApplyOp(OpBuilder& builder, LinearTransformOp raw,
                                Value transform) {
  OperationState state(raw.getLoc(),
                       ApplyPreparedLinearTransformOp::getOperationName());
  state.addOperands({raw.getCtx(), raw.getInput(), raw.getEvkMap(), transform,
                     raw.getOutput()});
  state.addTypes(raw.getResultTypes());
  state.addAttributes(raw->getAttrs());
  return builder.create(state);
}

struct CheddarPrepareLinearTransforms
    : impl::CheddarPrepareLinearTransformsBase<CheddarPrepareLinearTransforms> {
  void runOnOperation() override {
    ModuleOp module = getOperation();
    SmallVector<func::FuncOp> evalFuncs;
    module.walk([&](func::FuncOp func) {
      if (func.getName().ends_with("__preprocessed") &&
          !func.getOps<LinearTransformOp>().empty())
        evalFuncs.push_back(func);
    });

    for (func::FuncOp evalFunc : evalFuncs) {
      std::string base = evalFunc.getName()
                             .drop_back(StringRef("__preprocessed").size())
                             .str();
      auto packFunc =
          module.lookupSymbol<func::FuncOp>(base + "__preprocessing");
      if (!packFunc) {
        evalFunc.emitOpError("has linear transforms but no paired ")
            << base << "__preprocessing function";
        signalPassFailure();
        return;
      }
      auto calls = findCallPair(module, packFunc, evalFunc);
      if (failed(calls)) {
        evalFunc.emitOpError(
            "could not find directly paired preprocessing wrapper calls");
        signalPassFailure();
        return;
      }
      func::CallOp oldPackCall = calls->first;
      func::CallOp oldEvalCall = calls->second;

      SmallVector<LinearTransformOp> rawTransforms(
          evalFunc.getOps<LinearTransformOp>());
      Value rawCtx = rawTransforms.front().getCtx();
      auto ctxArg = dyn_cast<BlockArgument>(rawCtx);
      if (!ctxArg || ctxArg.getOwner() != &evalFunc.getBody().front()) {
        rawTransforms.front().emitOpError(
            "expected linear-transform context to be a function argument");
        signalPassFailure();
        return;
      }
      unsigned ctxIndex = ctxArg.getArgNumber();
      Value wrapperCtx = oldEvalCall.getOperand(ctxIndex);
      if (failed(packFunc.insertArgument(packFunc.getNumArguments(),
                                         rawCtx.getType(), nullptr,
                                         packFunc.getLoc()))) {
        packFunc.emitOpError("failed to append context argument");
        signalPassFailure();
        return;
      }
      BlockArgument packCtx = packFunc.getArguments().back();

      // Map evaluation arguments that are also preprocessing inputs. This is
      // based on their common wrapper SSA operand rather than type or position,
      // so repeated weight tensor types remain unambiguous.
      IRMapping mapper;
      mapper.map(rawCtx, packCtx);
      for (auto [evalIndex, wrapperOperand] :
           llvm::enumerate(oldEvalCall.getOperands())) {
        auto evalArg = evalFunc.getArgument(evalIndex);
        for (auto [packIndex, packOperand] :
             llvm::enumerate(oldPackCall.getOperands())) {
          if (wrapperOperand == packOperand)
            mapper.map(evalArg, packFunc.getArgument(packIndex));
        }
      }

      SmallVector<Value> preparedValues;
      OpBuilder packBuilder(packFunc.getBody().front().getTerminator());
      OpBuilder evalBuilder(evalFunc.getContext());
      auto handleType = RankedTensorType::get(
          {}, LinearTransformType::get(evalFunc.getContext()));

      for (LinearTransformOp raw : rawTransforms) {
        Operation* diagonalRoot = raw.getDiagonals().getDefiningOp();
        if (!diagonalRoot) {
          raw.emitOpError(
              "expected cleartext diagonals to have a defining operation");
          signalPassFailure();
          return;
        }
        llvm::SetVector<Operation*> slice;
        BackwardSliceOptions options;
        options.omitBlockArguments = true;
        if (failed(getBackwardSlice(diagonalRoot, &slice, options))) {
          raw.emitOpError("failed to compute cleartext diagonal slice");
          signalPassFailure();
          return;
        }
        for (Operation* dependency : slice) {
          if (mapper.contains(dependency)) continue;
          Operation* cloned = packBuilder.clone(*dependency, mapper);
          mapper.map(dependency, cloned);
        }
        if (!mapper.contains(diagonalRoot)) {
          Operation* cloned = packBuilder.clone(*diagonalRoot, mapper);
          mapper.map(diagonalRoot, cloned);
        }
        Value clonedDiagonals = mapper.lookupOrNull(raw.getDiagonals());
        if (!clonedDiagonals) {
          raw.emitOpError(
              "could not clone cleartext diagonal construction into "
              "preprocessing");
          signalPassFailure();
          return;
        }

        auto empty = tensor::EmptyOp::create(packBuilder, raw.getLoc(),
                                             ArrayRef<int64_t>{},
                                             handleType.getElementType());
        Operation* prepare =
            createPrepareOp(packBuilder, raw.getLoc(), raw, packCtx,
                            clonedDiagonals, empty, handleType);
        Value prepared = prepare->getResult(0);
        preparedValues.push_back(prepared);
        appendFunctionResult(packFunc, handleType, prepared);

        auto inserted = evalFunc.insertArgument(
            evalFunc.getNumArguments(), handleType, nullptr, raw.getLoc());
        if (failed(inserted)) {
          raw.emitOpError("failed to append prepared-transform argument");
          signalPassFailure();
          return;
        }
        BlockArgument handleArg = evalFunc.getArguments().back();
        evalBuilder.setInsertionPoint(raw);
        Operation* apply = createApplyOp(evalBuilder, raw, handleArg);
        raw->replaceAllUsesWith(apply);
        raw.erase();
      }

      // Rebuild the two wrapper calls with the context input and prepared
      // handles. Existing storage results preserve their SSA users.
      OpBuilder callBuilder(oldPackCall);
      SmallVector<Value> packOperands(oldPackCall.getOperands());
      packOperands.push_back(wrapperCtx);
      auto newPackCall = func::CallOp::create(
          callBuilder, oldPackCall.getLoc(), packFunc.getName(),
          packFunc.getResultTypes(), packOperands);
      for (auto [oldResult, newResult] :
           llvm::zip(oldPackCall.getResults(), newPackCall.getResults()))
        oldResult.replaceAllUsesWith(newResult);

      callBuilder.setInsertionPoint(oldEvalCall);
      SmallVector<Value> evalOperands(oldEvalCall.getOperands());
      for (unsigned i = 0; i < preparedValues.size(); ++i)
        evalOperands.push_back(newPackCall.getResult(
            newPackCall.getNumResults() - preparedValues.size() + i));
      auto newEvalCall = func::CallOp::create(
          callBuilder, oldEvalCall.getLoc(), evalFunc.getName(),
          evalFunc.getResultTypes(), evalOperands);
      oldEvalCall.replaceAllUsesWith(newEvalCall.getResults());
      oldEvalCall.erase();
      oldPackCall.erase();
    }
  }
};

}  // namespace
}  // namespace mlir::heir::cheddar
