#include <cmath>
#include <cstdint>
#include <optional>
#include <string>
#include <utility>
#include <vector>

#include "gtest/gtest.h"  // from @googletest
#include "lib/Parameters/Cheddar/ParameterFile.h"
#include "llvm/include/llvm/Support/Error.h"  // from @llvm-project

namespace mlir {
namespace heir {
namespace cheddar {
namespace {

// A three-level residual chain with two terminal primes, as primegen32 lays
// 32-bit chains out, plus a two-level bootstrap chain above it.
constexpr const char* kCyclopsFile = R"(// main & terminal primes generated by:
//   python3 primegen32.py --log_scale 35 "quoted // not a comment"
{
  "schema": { "name": "cyclops.multi_profile_parameter_set", "major": 1, "minor": 0 },
  "ring_chain": {
    "log_default_scale": 35,
    "default_num_aux": 2,
    "level_specific_ks": false,
    "max_key_switch_aux": 3,
    "additional_base": [0, 1],
    "level_config": [[0, 2], [2, 1], [4, 0]],
    "boot": {
      "sparse_hamming_weight": 32,
      "num_stc_levels": 1,
      "num_eval_mod_levels": 0,
      "num_cts_levels": 1,
      "eval_mod": {"type": "cos_hk_even", "degree": 26, "inv_degree": 0, "log_message_ratio": 7},
      "level_config": [[3, 2], [5, 2]]
    },
    "terminal_primes": [30539777, 32899073],
    "main_primes": [969146369, 1172439041, 958136321, 1070727169, 1115815937],
    "auxiliary_primes": [964558849, 974258177, 972029953],
    "profiles": [
      { "log_degree": 13, "default_encryption_level": 0, "hamming_weight": 128, "max_log_pq": 216.25 },
      { "log_degree": 14, "default_encryption_level": 1, "hamming_weight": 256, "max_log_pq": 432.5 },
      { "log_degree": 15, "default_encryption_level": 2, "hamming_weight": 512, "max_log_pq": 865 },
      { "log_degree": 16, "default_encryption_level": 2, "hamming_weight": 1024, "max_log_pq": 1730 }
    ]
  }
})";

ParameterFile parseOrDie(const std::string& text) {
  llvm::Expected<ParameterFile> file = ParameterFile::parse(text, "test");
  if (!file) {
    ADD_FAILURE() << llvm::toString(file.takeError());
    return ParameterFile();
  }
  return std::move(*file);
}

TEST(CyclopsParameterFileTest, ParsesChain) {
  ParameterFile file = parseOrDie(kCyclopsFile);
  EXPECT_EQ(file.logDefaultScale, 35);
  EXPECT_EQ(file.wordBits(), 32);
  EXPECT_EQ(file.defaultNumAux, 2);
  EXPECT_EQ(file.levelSpecificKs, std::optional<bool>(false));
  EXPECT_EQ(file.maxKeySwitchAux, 3);
  EXPECT_EQ(file.additionalBase, (LevelLayout{0, 1}));
  // The residual chain, then the bootstrap levels.
  ASSERT_EQ(file.levels.size(), 5u);
  EXPECT_EQ(file.levels[1], (LevelLayout{2, 1}));
  EXPECT_EQ(file.levels[3], (LevelLayout{3, 2}));
  ASSERT_TRUE(file.boot.has_value());
  EXPECT_EQ(file.boot->numCtsLevels, 1);
  EXPECT_EQ(file.boot->numStcLevels, 1);
  EXPECT_EQ(file.boot->numEvalModLevels, 0);
  EXPECT_EQ(file.boot->sparseHammingWeight, 32);
  EXPECT_EQ(file.boot->endLevel, 2);
  EXPECT_TRUE(file.boot->evalMod.present);
  EXPECT_EQ(file.boot->evalMod.type, "cos_hk_even");
  EXPECT_EQ(file.boot->evalMod.degree, 26);
  EXPECT_EQ(file.boot->evalMod.interval, -1);
  EXPECT_EQ(file.boot->logMessageRatio, 7);
  ASSERT_EQ(file.profiles.size(), 4u);
  EXPECT_EQ(file.profiles[1].logDegree, 14);
  EXPECT_EQ(file.profiles[1].defaultEncryptionLevel, 1);
  EXPECT_DOUBLE_EQ(file.profiles[3].maxLogPq, 1730.0);
}

TEST(CyclopsParameterFileTest, SelectsProfiles) {
  ParameterFile file = parseOrDie(kCyclopsFile);
  const RingProfile* profile = file.selectProfile(0, 1, false);
  ASSERT_NE(profile, nullptr);
  EXPECT_EQ(profile->logDegree, 14);
  profile = file.selectProfile(15, 0, false);
  ASSERT_NE(profile, nullptr);
  EXPECT_EQ(profile->logDegree, 15);
  profile = file.selectProfile(0, 1, true);
  ASSERT_NE(profile, nullptr);
  EXPECT_EQ(profile->logDegree, 16);
  EXPECT_TRUE(file.hasBootstrap(*profile));
  EXPECT_FALSE(file.hasBootstrap(file.profiles[2]));
  EXPECT_EQ(file.selectProfile(0, 3, false), nullptr);
  EXPECT_EQ(file.selectProfile(17, 0, false), nullptr);
}

TEST(CyclopsParameterFileTest, LayoutAndModulusGrowth) {
  ParameterFile file = parseOrDie(kCyclopsFile);
  EXPECT_TRUE(file.prefixChains);
  const std::vector<LevelLayout>& full = file.levels;

  auto log2 = [](uint64_t prime) {
    return std::log2(static_cast<double>(prime));
  };
  const auto& main = file.mainPrimes;
  const auto& terminal = file.terminalPrimes;
  EXPECT_DOUBLE_EQ(file.log2ModulusGrowth(full, 0),
                   log2(terminal[0]) + log2(terminal[1]));
  // {0, 2} -> {2, 1}: two main primes added, the second terminal prime dropped.
  EXPECT_DOUBLE_EQ(file.log2ModulusGrowth(full, 1),
                   log2(main[0]) + log2(main[1]) - log2(terminal[1]));
  // {2, 1} -> {4, 0}.
  EXPECT_DOUBLE_EQ(file.log2ModulusGrowth(full, 2),
                   log2(main[2]) + log2(main[3]) - log2(terminal[0]));
  // {4, 0} -> {3, 2}: one main prime dropped, both terminal primes added.
  EXPECT_DOUBLE_EQ(file.log2ModulusGrowth(full, 3),
                   log2(terminal[0]) + log2(terminal[1]) - log2(main[3]));
  EXPECT_DOUBLE_EQ(file.log2ModulusGrowth(full, 4),
                   log2(main[3]) + log2(main[4]));
}

TEST(CyclopsParameterFileTest, RejectsMalformedFiles) {
  auto expectError = [](const std::string& text, const char* fragment) {
    llvm::Expected<ParameterFile> file = ParameterFile::parse(text, "test");
    ASSERT_FALSE(static_cast<bool>(file));
    std::string message = llvm::toString(file.takeError());
    EXPECT_NE(message.find(fragment), std::string::npos) << message;
  };
  std::string text = kCyclopsFile;
  expectError(text.replace(text.find("\"major\": 1"), 10, "\"major\": 2"),
              "schema major");
  text = kCyclopsFile;
  expectError(text.replace(text.find("[4, 0]"), 6, "[9, 0]"), "main primes");
  text = kCyclopsFile;
  expectError(text.replace(text.find("[2, 1]"), 6, "[0, 1]"),
              "more primes than the level below");
  text = kCyclopsFile;
  expectError(text.replace(text.find("\"num_cts_levels\": 1"), 19,
                           "\"num_cts_levels\": 2"),
              "num_cts_levels + num_eval_mod_levels + num_stc_levels");
  text = kCyclopsFile;
  expectError(
      text.replace(text.find("\"log_degree\": 16"), 16, "\"log_degree\": 17"),
      "contiguous chain");
  text = kCyclopsFile;
  expectError(
      text.replace(text.find("\"inv_degree\": 0"), 15, "\"inv_degree\": 2"),
      "inv_degree must be odd");
}

TEST(CyclopsParameterFileTest, DetectsWordSize) {
  std::string text = kCyclopsFile;
  text.replace(text.find("969146369"), 9, "36028797018963969");
  EXPECT_EQ(parseOrDie(text).wordBits(), 64);
}

// CHEDDAR's single-ring bootstrapping parameters: the default encryption
// level (4) is where SlotToCoeff starts, so the bootstrap lands one level
// below it, and CoeffToSlot and EvalMod take the two levels above it.
constexpr const char* kCheddarFile = R"({
  "log_degree": 16,
  "log_default_scale": 35,
  "boot": true,
  "dense_hamming_weight": 32768,
  "sparse_hamming_weight": 32,
  "num_cts_levels": 1,
  "num_stc_levels": 1,
  "terminal_primes": [30539777, 32899073],
  "main_primes": [969146369, 1172439041, 958136321, 1070727169, 1115815937, 1062862849],
  "auxiliary_primes": [964558849, 974258177],
  "default_encryption_level": 4,
  "level_config": [[0, 2], [2, 1], [4, 0], [3, 2], [5, 1], [6, 1], [6, 2]],
  "additional_base": [0, 0]
})";

TEST(CheddarParameterFileTest, ParsesChain) {
  ParameterFile file = parseOrDie(kCheddarFile);
  EXPECT_EQ(file.logDefaultScale, 35);
  EXPECT_EQ(file.wordBits(), 32);
  EXPECT_EQ(file.defaultNumAux, -1);
  EXPECT_FALSE(file.levelSpecificKs.has_value());
  ASSERT_EQ(file.levels.size(), 7u);
  EXPECT_FALSE(file.prefixChains);
  ASSERT_EQ(file.profiles.size(), 1u);
  EXPECT_EQ(file.profiles[0].logDegree, 16);
  EXPECT_EQ(file.profiles[0].defaultEncryptionLevel, 4);
  EXPECT_EQ(file.profiles[0].hammingWeight, 32768);
  ASSERT_TRUE(file.boot.has_value());
  EXPECT_EQ(file.boot->numCtsLevels, 1);
  EXPECT_EQ(file.boot->numStcLevels, 1);
  EXPECT_EQ(file.boot->numEvalModLevels, 1);
  EXPECT_EQ(file.boot->endLevel, 3);
  EXPECT_EQ(file.boot->sparseHammingWeight, 32);
  EXPECT_EQ(file.boot->logMessageRatio, -1);
  EXPECT_FALSE(file.boot->evalMod.present);
}

TEST(CheddarParameterFileTest, SelectsLevels) {
  ParameterFile file = parseOrDie(kCheddarFile);
  const RingProfile& ring = file.profiles[0];
  EXPECT_EQ(file.topLevel(ring, /*bootstraps=*/false), 4);
  EXPECT_EQ(file.topLevel(ring, /*bootstraps=*/true), 3);
  EXPECT_EQ(file.selectProfile(0, 4, false), &ring);
  EXPECT_EQ(file.selectProfile(0, 4, true), nullptr);
}

TEST(CheddarParameterFileTest, RejectsMalformedFiles) {
  auto expectError = [](const std::string& text, const char* fragment) {
    llvm::Expected<ParameterFile> file = ParameterFile::parse(text, "test");
    ASSERT_FALSE(static_cast<bool>(file));
    std::string message = llvm::toString(file.takeError());
    EXPECT_NE(message.find(fragment), std::string::npos) << message;
  };
  std::string text = kCheddarFile;
  expectError(text.replace(text.find("\"num_cts_levels\": 1"), 19,
                           "\"num_cts_levels\": 3"),
              "cannot hold the bootstrap");
  text = kCheddarFile;
  expectError(text.replace(text.find("\"default_encryption_level\": 4"), 29,
                           "\"default_encryption_level\": 9"),
              "default_encryption_level is outside level_config");
  text = kCheddarFile;
  expectError(text.replace(text.find("[6, 2]"), 6, "[5, 0]"),
              "more primes than the level below");
}

}  // namespace
}  // namespace cheddar
}  // namespace heir
}  // namespace mlir
